"""
Project Euler Problem 12
========================

The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
28. The first ten terms would be:

                 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

   1: 1
   3: 1,3
   6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five
divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""

import math

def find_tri(n):
	return sum(range(1,n+1))

def num_factors(n):
	count = 0
	for i in range(1, int(math.ceil(n ** 0.5))):
		if n % i == 0: count += 1 
	count = count * 2
	if int(n ** 0.5) ** 2 == n: count += 1
	return count

def tri_divisors(n):
	index = 1
	while num_factors(find_tri(index)) <= n: index += 1
	return find_tri(index)

print tri_divisors(500)
