"""
Project Euler Problem 44
========================

Pentagonal numbers are generated by the formula, P[n]=n(3n-1)/2. The first
ten pentagonal numbers are:

               1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P[j] and P[k], for which their sum
and difference is pentagonal and D = |P[k] - P[j]| is minimised; what is
the value of D?
"""

size = 10000
pent = [i*(3*i-1)/2 for i in xrange(1, size)]
t = dict.fromkeys(pent, 1)
found = False

for idx in xrange(size): 
	for idy in xrange(idx, 0, -1):
		d = pent[idx] - pent[idy]
		s = pent[idx] + pent[idy]
		if d in t and s in t: 
			found = True
			print pent[idx] - pent[idy]
	if found:
		break
				

